### ISSUE TITLE
Rgrep on windows output "File not found - *~"

### ISSUE THREAD

**Issue by bernecg** [yegappan/grep#3]
When using Recursive grep (like Rgrep) on Windows (in this case, 10). The output is always the message "File not found - *~".
The workaround was to use Grep with optin -r. 

Complete output:
```
|| [Search results for pattern: isNullOrEmpty]
|| 
|| C:\Users\foo\Work\src>find "C:\Users\foo\Work\src" -type d ( -name RCS -o -name CVS -o -name SCCS ) -prune -o -type f ! -name *~ ! -name *,v ! -name s.* ( -name * ) -print0   | xargs -0 grep -rni -s -n -- isNullOrEmpty NUL 
|| File not found - *~
```

**Comment by yegappan** [comment]
It looks like you are trying to use the find utility that is bundled with MS-Windows.
The grep plugin needs the GNU find utility (https://www.gnu.org/software/findutils).

You need to install the GNU findutils for MS-Windows (http://gnuwin32.sourceforge.net/packages/findutils.htm) and set the Grep_Find_Path Vim variable to point to the location
of the find utility.

Another alternative to the above is to use ":Findstr" command from the
latest version of the grep plugin. This relies on the findstr utility which
is bundled with MS-Windows. You can use the "/S" flag to search recursively.

:Findstr /S <your_pattern> *.java
