### ISSUE TITLE
Bgrep not working

### ISSUE THREAD

**Issue by embear** [yegappan/grep#6]
All commands that map to `grep#runGrepSpecial()` are not working for me. The following code tries to use `a:grep_cmd` which is not defined as it is not in the argument list.
https://github.com/yegappan/grep/blob/783819d20e7ff17a6b27a2aec2bc2b71ea6e634d/autoload/grep.vim#L806
This line seems to be a copy of `grep#runGrep()`.

**Comment by yegappan** [comment]
Thanks for reporting the bug. I have merged your changes.
